# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 968280b4245862a1271b03071ea18043162d3099fb1de5b0c7342891fb81c4262abb20402944df231dd7921563193d49913cc34ca28b729da488827f5bca9a47

test:
  secret_key_base: b68d653873fa04cf32971f563d4428cadb6bdab00b86ab8cee7b28ca3fc6d37a2937b6c9e61413fd4dba1dd9e2ef24ea50e34be3271355ccf347f81e0455aeb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
